require("dotenv").config()
// const pinata=require('./pinata/pinata')
// const {pinJson,pinImage}=require("./utils/ipfs")(pinata)
// const web3=require('./web3/web3')
// const {signContent,recoverAccountNo}=require("./utils/signContent")(web3)
const express=require('express')
const retailer=require('./retailer/retailer_server')
const app=express()
app.use("/retailer",retailer)
app.listen(8000,()=>console.log('ready!!!'))