require("dotenv").config()
const express = require('express')
const retailer = require('./retailer/retailer_server')
const app = express()
const path = require('path')

app.set('view engine', 'ejs')
app.use("/retailer", retailer)
app.use("/retailer", express.static(path.join(__dirname, "views", "static")))
app.listen(8000, () => console.log('ready!!!'))